# Based on the Goreleaser configuration provided at:
# https://github.com/hashicorp/terraform-provider-scaffolding
#
# Artifacts must be produced matching the layout described at:
# https://www.terraform.io/docs/registry/providers/publishing.html
before:
  hooks:
    - go mod tidy
    - ./scripts/completions.sh
builds:
- env:
    - CGO_ENABLED=0
  mod_timestamp: '{{ .CommitTimestamp }}'
  flags:
    - -trimpath
  ldflags:
    - '-s -w -X  github.com/castai/cli/pkg/version.Version={{.Version}} -X  github.com/castai/cli/pkg/version.Commit={{.Commit}}'
  goos:
    - windows
    - linux
    - darwin
  goarch:
    - amd64
    - arm64
  binary: 'cast'
archives:
- format: zip
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
  files:
    - README.md
    - LICENSE
    - completions/*
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256
signs:
  - artifacts: checksum
    args:
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"
release:
  draft: false
changelog:
  skip: true
brews:
  - tap:
      owner: castai
      name: homebrew-tap
    folder: Formula
    homepage: "https://cast.ai"
    description: Multiple clouds in one K8s cluster. Best combination of everything in cloud
    license: Apache License
    test: |
      system "#{bin}/cast version"
    install: |-
      bin.install "cast"
      bash_completion.install "completions/cast.bash" => "cast"
      zsh_completion.install "completions/cast.zsh" => "_cast"
      fish_completion.install "completions/cast.fish"
